export const ArtificialIntelligence = [
  {
    category: "AI-Powered Virtual Assistant",
    features: [
      {
        name: "Natural language understanding for voice and text commands",
        manDays: "8-16 days",
        totalManDays: 24,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Task automation and scheduling",
        manDays: "6-14 days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Information retrieval and recommendations",
        manDays: "8-16 days",
        totalManDays: 24,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Multimodal interaction (voice, text, and visuals)",
        manDays: "6-14 days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AI-Powered Customer Support Chatbot",
    features: [
      {
        name: "Natural language processing for understanding customer queries",
        manDays: "8-16 days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Predefined responses and knowledge base integration",
        manDays: "8-16 days",
        totalManDays: 32,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Escalation to human agents when necessary",
        manDays: "8-16 days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Sentiment analysis for gauging customer satisfaction",
        manDays: "8-16 days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AI-Driven Personalized Content Recommendations",
    features: [
      {
        name: "User profiling and behavior analysis",
        manDays: "6-12 days",
        totalManDays: 24,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Content recommendation algorithms",
        manDays: "6-12 days",
        totalManDays: 24,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Real-time content updates",
        manDays: "6-12 days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "A/B testing and performance analytics",
        manDays: "6-12 days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AI-Powered Fraud Detection",
    features: [
      {
        name: "Anomaly detection in financial transactions",
        manDays: "10-20 days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Pattern recognition for identifying fraudulent activities",
        manDays: "10-20 days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Real-time alerts and risk scoring",
        manDays: "10-20 days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Historical data analysis for fraud prevention",
        manDays: "10-20 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AI-Enhanced Image and Video Analysis",
    features: [
      {
        name: "Object detection and tracking",
        manDays: "8-16 days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Facial recognition and emotion analysis",
        manDays: "8-16 days",
        totalManDays: 28,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Content moderation and filtering",
        manDays: "8-16 days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Action recognition and event detection",
        manDays: "8-16 days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AI-Driven Predictive Maintenance",
    features: [
      {
        name: "Sensor data integration",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Predictive analytics for equipment health",
        manDays: "12-24 days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Automated maintenance scheduling",
        manDays: "12-24 days",
        totalManDays: 24,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Cost optimization and resource allocation",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AI-Enhanced Healthcare Diagnostics",
    features: [
      {
        name: "Medical image analysis (X-rays, MRIs, CT scans)",
        manDays: "16-30 days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Disease detection and diagnosis",
        manDays: "16-30 days",
        totalManDays: 25,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Treatment recommendations",
        manDays: "16-30 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Patient outcome prediction",
        manDays: "16-30 days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
];
