export const augmentedReality = [
  {
    category: "AR Mobile App for Product Visualization",
    features: [
      {
        name: "Markerless AR for product placement",
        manDays: "75-150 man-days",
        totalManDays: 65,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Realistic 3D models and animations",
        manDays: "75-150 man-days",
        totalManDays: 75,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Interactive product exploration",
        manDays: "75-150 man-days",
        totalManDays: 75,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Integration with e-commerce platforms for virtual try-ons",
        manDays: "75-150 man-days",
        totalManDays: 70,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AR Training and Simulation Application",
    features: [
      {
        name: "Interactive AR simulations",
        manDays: "100-188 man-days",
        totalManDays: 180,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Task-specific training modules",
        manDays: "100-188 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Realistic 3D models and environments",
        manDays: "100-188 man-days",
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Performance tracking and feedback",
        manDays: "100-188 man-days",
        totalManDays: 85,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AR Navigation and Wayfinding App",
    features: [
      {
        name: "Indoor and outdoor AR navigation",
        manDays: "75-150 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Real-time location tracking",
        manDays: "75-150 man-days",
        totalManDays: 75,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Interactive points of interest (POIs)",
        manDays: "75-150 man-days",
        totalManDays: 70,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Integration with mapping services",
        manDays: "75-150 man-days",
        totalManDays: 70,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AR Marketing and Advertising Campaign",
    features: [
      {
        name: "Interactive AR ad experiences",
        manDays: "50-100 man-days",
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Gamified marketing campaigns",
        manDays: "50-100 man-days",
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Scannable AR markers or QR codes",
        manDays: "50-100 man-days",
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Integration with social media sharing",
        manDays: "50-100 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AR Educational Content and Learning Platform",
    features: [
      {
        name: "AR-enhanced educational content",
        manDays: "100-188 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Interactive 3D models and simulations",
        manDays: "100-188 man-days",
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Real-time quizzes and assessments",
        manDays: "100-188 man-days",
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Progress tracking and analytics",
        manDays: "100-188 man-days",
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
  {
    category: "AR Interior Design and Home Improvement Tool",
    features: [
      {
        name: "Room scanning and measurement",
        manDays: "75-150 man-days",
        totalManDays: 70,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Virtual furniture placement and customization",
        manDays: "75-150 man-days",
        totalManDays: 70,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "AR-based design recommendations",
        manDays: "75-150 man-days",
        totalManDays: 75,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
      {
        name: "Integration with shopping and home improvement apps",
        manDays: "75-150 man-days",
        totalManDays: 70,
        numResources: 2,
        devRequired: ["Machine Learning Engineer"],
        recommendedStack: ["TensorFLow", "Pytorch"],
      },
    ],
  },
];

