export const ComputerVision = [
  {
    category: "Facial Recognition System",
    features: [
      {
        name: "Face detection and alignment",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Facial feature extraction",
        totalManDays: 120,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Identity verification and recognition",
        totalManDays: 150,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Liveness detection for security applications",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
    ],
  },
  {
    category: "Object Detection and Tracking System",
    features: [
      {
        name: "Object detection using deep learning models",
        totalManDays: 120,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["YOLO", "PyTorch"],
      },
      {
        name: "Real-time tracking and localization",
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["YOLO", "PyTorch"],
      },
      {
        name: "Multiple object recognition and tracking",
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["YOLO", "PyTorch"],
      },
      {
        name: "Integration with cameras and sensors",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Software Developer"],
        recommendedStack: ["OpenCV", "Python"],
      },
    ],
  },
  {
    category: "Image Segmentation and Semantic Segmentation",
    features: [
      {
        name: "Image segmentation for object separation",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "PyTorch"],
      },
      {
        name: "Semantic segmentation for pixel-level object classification",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "PyTorch"],
      },
      {
        name: "Medical image segmentation for diagnostics",
        totalManDays: 120,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "PyTorch"],
      },
      {
        name: "Customizable segmentation models",
        totalManDays: 130,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "PyTorch"],
      },
    ],
  },
  {
    category: "Gesture Recognition System",
    features: [
      {
        name: "Hand and gesture detection",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Gesture classification and recognition",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Real-time tracking and response",
        totalManDays: 120,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Integration with interactive systems",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Software Developer"],
        recommendedStack: ["OpenCV", "Python"],
      },
    ],
  },
  {
    category: "Content Moderation and Filtering System",
    features: [
      {
        name: "Image and video content analysis",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Offensive content detection",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Age-appropriate content filtering",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["OpenCV", "TensorFlow"],
      },
      {
        name: "Integration with online platforms",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Software Developer"],
        recommendedStack: ["OpenCV", "Python"],
      },
    ],
  },
  {
    category: "Autonomous Drone Navigation",
    features: [
      {
        name: "Obstacle detection and avoidance",
        totalManDays: 160,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["ROS", "PyTorch"],
      },
      {
        name: "Path planning and mapping",
        totalManDays: 160,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["ROS", "PyTorch"],
      },
      {
        name: "Autonomous flight control",
        totalManDays: 160,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["ROS", "PyTorch"],
      },
      {
        name: "Real-time environmental analysis",
        totalManDays: 160,
        numResources: 2,
        devRequired: ["Computer Vision Engineer", "Machine Learning Engineer"],
        recommendedStack: ["ROS", "PyTorch"],
      },
    ],
  },
];

