export const DeepLearning = [
  {
    category: "Image Recognition and Classification System",
    features: [
      {
        name: "Convolutional Neural Networks (CNNs) for image analysis",
        manDays: "50-100 man-days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Computer Vision Engineer"],
        recommendedStack: ["TensorFlow", "Keras"],
      },
      {
        name: "Multiple object recognition and classification",
        manDays: "50-100 man-days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Computer Vision Engineer"],
        recommendedStack: ["TensorFlow", "Keras"],
      },
      {
        name: "Real-time image processing",
        manDays: "50-100 man-days",
        totalManDays: 120,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Computer Vision Engineer"],
        recommendedStack: ["TensorFlow", "OpenCV"],
      },
      {
        name: "Integration with cameras or image sources",
        manDays: "50-100 man-days",
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Software Developer"],
        recommendedStack: ["Python", "OpenCV"],
      },
    ],
  },
  {
    category: "Natural Language Processing (NLP) for Chatbots",
    features: [
      {
        name: "Recurrent Neural Networks (RNNs) or Transformers for NLP tasks",
        manDays: "50-100 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "NLP Engineer"],
        recommendedStack: ["PyTorch", "Hugging Face Transformers"],
      },
      {
        name: "Sentiment analysis, intent recognition, and dialogue generation",
        manDays: "50-100 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "NLP Engineer"],
        recommendedStack: ["PyTorch", "Hugging Face Transformers"],
      },
      {
        name: "Multi-language support",
        manDays: "50-100 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "NLP Engineer"],
        recommendedStack: ["PyTorch", "Hugging Face Transformers"],
      },
      {
        name: "Integration with chat platforms",
        manDays: "50-100 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Software Developer"],
        recommendedStack: ["Python", "Dialogflow"],
      },
    ],
  },
  {
    category: "Speech Recognition and Voice Assistant",
    features: [
      {
        name: "Automatic Speech Recognition (ASR) models",
        manDays: "60-120 man-days",
        totalManDays: 120,
        numResources: 2,
        devRequired: [
          "Machine Learning Engineer",
          "Speech Recognition Engineer",
        ],
        recommendedStack: ["TensorFlow", "Kaldi"],
      },
      {
        name: "Voice command recognition",
        manDays: "60-120 man-days",
        totalManDays: 120,
        numResources: 2,
        devRequired: [
          "Machine Learning Engineer",
          "Speech Recognition Engineer",
        ],
        recommendedStack: ["TensorFlow", "Kaldi"],
      },
      {
        name: "Multilingual support",
        manDays: "60-120 man-days",
        totalManDays: 120,
        numResources: 2,
        devRequired: [
          "Machine Learning Engineer",
          "Speech Recognition Engineer",
        ],
        recommendedStack: ["TensorFlow", "Kaldi"],
      },
      {
        name: "Integration with virtual assistants (e.g., Alexa or Google Assistant)",
        manDays: "60-120 man-days",
        totalManDays: 120,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Software Developer"],
        recommendedStack: ["Python", "Google Cloud Speech-to-Text"],
      },
    ],
  },
  {
    category: "Image Generation and Style Transfer",
    features: [
      {
        name: "Generative Adversarial Networks (GANs) or Variational Autoencoders (VAEs)",
        manDays: "50-100 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Computer Vision Engineer"],
        recommendedStack: ["TensorFlow", "PyTorch"],
      },
      {
        name: "Image synthesis and artistic style transfer",
        manDays: "50-100 man-days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Computer Vision Engineer"],
        recommendedStack: ["TensorFlow", "PyTorch"],
      },
      {
        name: "Customizable parameters for image generation",
        manDays: "50-100 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Computer Vision Engineer"],
        recommendedStack: ["TensorFlow", "PyTorch"],
      },
      {
        name: "Integration with image editing software or applications",
        manDays: "50-100 man-days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Machine Learning Engineer", "Software Developer"],
        recommendedStack: ["Python", "Adobe Creative Cloud SDK"],
      },
    ],
  },
  {
    category: "Medical Image Analysis for Diagnostics",
    features: [
      {
        name: "Deep learning models for medical image analysis (e.g., CNNs)",
        manDays: "80-150 man-days",
        totalManDays: 150,
        numResources: 2,
        devRequired: [
          "Machine Learning Engineer",
          "Medical Imaging Specialist",
        ],
        recommendedStack: ["TensorFlow", "PyTorch"],
      },
      {
        name: "Disease detection, localization, and classification",
        manDays: "80-150 man-days",
        totalManDays: 140,
        numResources: 2,
        devRequired: [
          "Machine Learning Engineer",
          "Medical Imaging Specialist",
        ],
        recommendedStack: ["TensorFlow", "PyTorch"],
      },
      {
        name: "Integration with medical imaging equipment",
        manDays: "80-150 man-days",
        totalManDays: 150,
        numResources: 2,
        devRequired: [
          "Machine Learning Engineer",
          "Medical Imaging Specialist",
        ],
        recommendedStack: ["TensorFlow", "PyTorch"],
      },
      {
        name: "Regulatory compliance for healthcare applications",
        manDays: "80-150 man-days",
        totalManDays: 150,
        numResources: 2,
        devRequired: [
          "Machine Learning Engineer",
          "Medical Imaging Specialist",
        ],
        recommendedStack: ["TensorFlow", "PyTorch"],
      },
    ],
  },
];
