export const DigitalSignage = [
  {
    category: "CMS",
    features: [
      {
        name: "Content Upload and Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
        priority: 1,
      },
      {
        name: "Playlist Creation",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js"],
        priority: 1,
      },
      {
        name: "Screen Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js"],
        priority: 1,
      },
      {
        name: "Content Types (Video, Image, Web Pages, RSS Feeds)",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
        priority: 1,
      },
      {
        name: "Content Synchronization",
        manDays: "5+10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["Node.js", "Docker"],
        priority: 1,
      },
      {
        name: "User Access Control",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Backend Developer", "Frontend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 1,
      },
      {
        name: "Monitoring and Proof of Play",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Frontend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Integration and Compatibility",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Frontend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Content Templates",
        manDays: "10+5 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Emergency Alerts",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Content Preview",
        manDays: "3+3 Man Days",
        totalManDays: 6,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 1,
      },
      {
        name: "Mobile Accessibility",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Content Approval Workflow",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Scalability",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Security and Access Control",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Content Expiry and Archiving",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Content Tagging and Search",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
      {
        name: "Cost Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
        priority: 0,
      },
    ],
  },
  {
    category: "Player",
    features: [
      {
        name: "Electron Player",
        manDays: "",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["Electron", "React", "HTML", "CSS", "JavaScript"],
        subFeatures: [
          "Support for all environments - Windows/Linux",
          "Content Compatibility",
          "Network Connectivity",
          "Remote Control",
          "Interactivity",
          "Streaming Services",
        ],
        priority: 1,
      },
      {
        name: "Kiosk Player",
        manDays: "",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["Node.js", "Html", "JS"],
        subFeatures: [
          "Interactivity",
          "Content Compatibility",
          "Hardware Integration",
          "Content Scheduling",
          "Offline Playback",
          "Content Synchronization",
        ],
        priority: 1,
      },
      {
        name: "PC-Based Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Dot.Net", "WPF"],
        subFeatures: [
          "Operating System Compatibility",
          "Content Compatibility",
          "Hardware Integration",
          "Remote Management",
          "Security",
          "Content Scheduling",
          "Interactivity",
          "Multi-Screen Support",
          "Offline Playback",
        ],
        priority: 1,
      },
      {
        name: "Hardware Media Player",
        manDays: "",
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Depends on Hardware"],
        subFeatures: [
          "Dedicated Hardware",
          "Content Playback",
          "Remote Monitoring",
          "Security",
          "Network Connectivity",
          "Content Synchronization",
          "Playback Scheduling",
          "Video Wall Support",
        ],
        priority: 1,
      },
      {
        name: "Smart TV Player",
        manDays: "",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Android"],
        subFeatures: [
          "Built-In Software",
          "Content Compatibility",
          "Network Connectivity",
          "App Store Access",
          "Remote Control",
          "Interactivity",
          "Streaming Services",
        ],
        priority: 1,
      },
      {
        name: "Set-Top Box (STB)",
        manDays: "",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Depends on the Setup-Box"],
        subFeatures: [
          "External Device",
          "Content Playback",
          "Network Connectivity",
          "Remote Control",
          "Security",
          "Content Scheduling",
        ],
        priority: 1,
      },
      {
        name: "Raspberry Pi Player",
        manDays: "",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Electron", "WPF"],
        subFeatures: [
          "Raspberry Pi Compatibility",
          "Content Playback",
          "Network Connectivity",
          "Remote Management",
          "Low-Cost Solution",
          "Energy-Efficient",
        ],
        priority: 1,
      },
      {
        name: "SoC (System on Chip) Display",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Depends on OS"],
        subFeatures: [
          "Embedded Player",
          "Content Playback",
          "Remote Control",
          "Network Connectivity",
          "Simplified Installation",
        ],
        priority: 1,
      },
      {
        name: "Cloud-Based Player",
        manDays: "",
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Js", "AWS"],
        subFeatures: [
          "Cloud Hosting",
          "Content Distribution",
          "Remote Management",
          "Scalability",
          "Content Scheduling",
          "Content Security",
        ],
        priority: 1,
      },
      {
        name: "HTML5 Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Js", "HTML"],
        subFeatures: [
          "Web-Based Content",
          "Content Compatibility",
          "Web Browser",
          "Remote Management",
          "Network Connectivity",
        ],
        priority: 1,
      },
      {
        name: "Mobile Device Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Android"],
        subFeatures: [
          "Mobile App",
          "Content Playback",
          "Content Scheduling",
          "Remote Management",
          "Portability",
        ],
        priority: 1,
      },
      {
        name: "Video Wall Controller",
        manDays: "",
        totalManDays: 100,
        numResources: 3,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Js"],
        subFeatures: [
          "Video Wall Configuration",
          "Content Distribution",
          "Synchronization",
          "Interactive Features",
          "Remote Control",
        ],
        priority: 1,
      },
    ],
  },
];
