export const DigitalSignage = [
  {
    category: "CMS",
    features: [
      {
        name: "Content Upload and Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Playlist Creation",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Screen Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Content Types (Video, Image, Web Pages, RSS Feeds)",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 3,
        devRequired: [
          "Frontend Developer",
          "Backend Developer",
          "Machine Learning Engineer",
        ],
        recommendedStack: ["React.js", "Node.js", "MongoDB", "TensorFlow"],
      },
      {
        name: "Content Synchronization",
        manDays: "5+10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend Developer", "DevOps Engineer"],
        recommendedStack: ["Node.js", "Docker"],
      },
      {
        name: "User Access Control",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Backend Developer", "Frontend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Monitoring and Reporting",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Frontend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Integration and Compatibility",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Frontend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Content Templates",
        manDays: "10+5 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Emergency Alerts",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Content Preview",
        manDays: "3+3 Man Days",
        totalManDays: 6,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Mobile Accessibility",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Content Approval Workflow",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Scalability",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Security and Access Control",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Content Expiry and Archiving",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Content Tagging and Search",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Cost Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
    ],
  },
  {
    category: "Player",
    features: [
      {
        name: "PC-Based Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js", "Electron"],
      },
      {
        name: "Hardware Media Player",
        manDays: "",
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Smart TV Player",
        manDays: "",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Set-Top Box (STB)",
        manDays: "",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Raspberry Pi Player",
        manDays: "",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "SoC (System on Chip) Display",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Cloud-Based Player",
        manDays: "",
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js", "AWS"],
      },
      {
        name: "HTML5 Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Mobile Device Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Video Wall Controller",
        manDays: "",
        totalManDays: 100,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
    ],
  },
];
