export const DigitalSignage = [
  {
    category: "CMS",
    features: [
      {
        name: "Content Upload and Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Playlist Creation",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Frontend"],
      },
      {
        name: "Screen Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Frontend"],
      },
      {
        name: "Content Types (Video, Image, Web Pages, RSS Feeds)",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 3,
        devRequired: ["Frontend", "Backend", "Machine Learning Engineer"],
      },
      {
        name: "Content Synchronization",
        manDays: "5+10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend", "DevOps Engineer"],
      },
      {
        name: "User Access Control",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Backend", "Frontend"],
      },
      {
        name: "Monitoring and Reporting",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend", "Frontend"],
      },
      {
        name: "Integration and Compatibility",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend", "Frontend"],
      },
      {
        name: "Content Templates",
        manDays: "10+5 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Emergency Alerts",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Content Preview",
        manDays: "3+3 Man Days",
        totalManDays: 6,
        numResources: 1,
        devRequired: ["Frontend"],
      },
      {
        name: "Mobile Accessibility",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Content Approval Workflow",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Scalability",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Security and Access Control",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Content Expiry and Archiving",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Content Tagging and Search",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
      {
        name: "Cost Management",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend", "Backend"],
      },
    ],
  },
  {
    category: "Player",
    features: [
      {
        name: "PC-Based Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "Hardware Media Player",
        manDays: "",
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "Smart TV Player",
        manDays: "",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "Set-Top Box (STB)",
        manDays: "",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "Raspberry Pi Player",
        manDays: "",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "SoC (System on Chip) Display",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "Cloud-Based Player",
        manDays: "",
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "HTML5 Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "Mobile Device Player",
        manDays: "",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend"],
      },
      {
        name: "Video Wall Controller",
        manDays: "",
        totalManDays: 100,
        numResources: 1,
        devRequired: ["Backend"],
      },
      // ... other features with updated fields
    ],
  },
];

export const DigitalSignageResources = [
  {
    role: "Frontend Developer",
    skills: ["React", "HTML5", "CSS3", "JavaScript"],
  },
  {
    role: "Backend Developer",
    skills: ["Node.js", "Express.js", "MongoDB"],
  },
  {
    role: "DevOps Engineer",
    skills: ["Docker", "AWS", "Jenkins", "Ansible"],
  },
  {
    role: "Machine Learning Engineer",
    skills: ["Python", "TensorFlow", "scikit-learn"],
  },
  {
    role: "UI/UX Designer",
    skills: ["UI/UX Design", "Prototyping"],
  },
];

export const DigitalSignageTechStack = [
  "React.js",
  "Node.js",
  "Express.js",
  "MongoDB",
  "Docker",
  "AWS",
  "Jenkins",
  "Ansible",
  "Python",
  "TensorFlow",
  "scikit-learn",
  "UI/UX Design",
];
