export const ECommerce = [
  {
    category: "Product Management",
    features: [
      {
        name: "Product catalog and listing",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Inventory management",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Product search and filtering",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Elasticsearch"],
      },
      {
        name: "Product reviews and ratings",
        manDays: "8-16 days",
        totalManDays: 14,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Product recommendations",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Machine Learning"],
      },
    ],
  },
  {
    category: "Shopping Cart and Checkout",
    features: [
      {
        name: "Add to cart and cart management",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Checkout process",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Stripe"],
      },
      {
        name: "Payment processing",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Stripe"],
      },
      {
        name: "Order confirmation and tracking",
        manDays: "8-16 days",
        totalManDays: 14,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
    ],
  },
  {
    category: "User Accounts and Authentication",
    features: [
      {
        name: "User registration and login",
        manDays: "8-16 days",
        totalManDays: 14,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Firebase"],
      },
      {
        name: "User profiles and preferences",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
      {
        name: "Password reset and security",
        manDays: "8-16 days",
        totalManDays: 14,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Firebase"],
      },
    ],
  },
  {
    category: "Search and Navigation",
    features: [
      {
        name: "Site search functionality",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Elasticsearch"],
      },
      {
        name: "Navigation and filters",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Elasticsearch"],
      },
    ],
  },
  {
    category: "Reviews and Ratings",
    features: [
      {
        name: "Customer reviews and ratings",
        manDays: "12-24 days",
        totalManDays: 18,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
    ],
  },
  {
    category: "Order Management",
    features: [
      {
        name: "Order history and tracking",
        manDays: "12-24 days",
        totalManDays: 18,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
    ],
  },
  {
    category: "Security and Compliance",
    features: [
      {
        name: "Payment security and compliance",
        manDays: "12-24 days",
        totalManDays: 18,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "Stripe"],
      },
    ],
  },
  {
    category: "Admin Dashboard",
    features: [
      {
        name: "Product and order management",
        manDays: "12-24 days",
        totalManDays: 18,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js", "MongoDB"],
      },
    ],
  },
];
