export const Fintech = [
  {
    category: "Digital Payments and Transfers",
    features: [
      {
        name: "Ease of Use",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 2,
        devRequired: "UI/UX Designer, Mobile App Developer",
      },
      {
        name: "Security",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: "Security Expert, Backend Developer",
      },
      {
        name: "Payment Methods",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
      },
      {
        name: "Mobile Payments",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: "Mobile App Developer, UI/UX Designer",
      },
      {
        name: "International Transfers",
        manDays: "60-120 man-days",
        totalManDays: 100,
        numResources: 2,
        devRequired: "Backend Developer, Security Expert",
      },
      {
        name: "Payment Scheduling",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
      },
      {
        name: "Transaction History",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 2,
        devRequired: "Backend Developer, Data Analyst",
      },
      {
        name: "Notifications",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: "Backend Developer",
      },
      {
        name: "Split and Group Payments",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
      },
      {
        name: "Bill Payment Services",
        manDays: "60-120 man-days",
        totalManDays: 120,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
      },
      {
        name: "Payment Request",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: "Backend Developer",
      },
      {
        name: "Instant Transfers",
        manDays: "40-80 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
      },
      {
        name: "P2P Transfers",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
      },
      {
        name: "Merchant Integration",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
      },
      {
        name: "Rewards and Loyalty Programs",
        manDays: "30-60 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
      },
      {
        name: "Customer Support",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: "Backend Developer",
      },
      {
        name: "Account Management",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: "Backend Developer",
      },
      {
        name: "Regulatory Compliance",
        manDays: "Ongoing and may require dedicated resources",
        totalManDays: 20,
        numResources: 1,
        devRequired: "Security Expert",
      },
      {
        name: "Accessibility",
        manDays: "Ongoing and integrated throughout development",
        totalManDays: 20,
        numResources: 1,
        devRequired: "UI/UX Designer",
      },
      {
        name: "Cross-Platform Compatibility",
        manDays: "30-60 man-days per platform (iOS, Android, web)",
        totalManDays: 40,
        numResources: 3,
        devRequired: "UI/UX Designer, Mobile App Developer, Backend Developer",
      },
    ],
  },
  {
    category: "Online Lending and Crowdfunding",
    features: [
      {
        name: "User Registration and Profile Management",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Loan Application",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Credit Scoring and Risk Assessment",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
      },
      {
        name: "Loan Approval and Disbursement",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Loan Repayment and Amortization",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Investor Account Management",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Loan Listing and Marketplace",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Payment Processing and Escrow",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Payment Integration Specialist"],
      },
      {
        name: "Auto-Invest Features",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
      },
      {
        name: "Loan Servicing and Collections",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Collections Specialist"],
      },
      {
        name: "Secondary Market Trading",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Marketplace Developer"],
      },
      {
        name: "Reporting and Analytics",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Notifications and Alerts",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Regulatory Compliance",
        manDays: "Ongoing and may require dedicated resources",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Compliance Specialist"],
      },
      {
        name: "Customer Support",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Customer Support Specialist"],
      },
      {
        name: "Security and Fraud Prevention",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Mobile App Development",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Mobile App Developer", "UI/UX Designer"],
      },
      {
        name: "Investor and Borrower Onboarding",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "KYC/AML Verification",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Compliance Specialist"],
      },
      {
        name: "Documentation and Legal Compliance",
        manDays: "30-60 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Legal Specialist"],
      },
    ],
  },
  {
    category: "Cryptocurrency and Blockchain",
    features: [
      {
        name: "User Registration and Wallet Creation",
        manDays: "10-20 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Cryptocurrency Transactions",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Cryptocurrency Exchange Integration",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Exchange Integration Specialist"],
      },
      {
        name: "Multi-Currency Wallet",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Security and Encryption",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Private Key Management",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Cryptocurrency Price Tracking",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Trading Features (Buy/Sell Orders)",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Trading Specialist"],
      },
      {
        name: "Liquidity and Order Matching",
        manDays: "40-80 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Trading Specialist"],
      },
      {
        name: "KYC/AML Verification",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Compliance Specialist"],
      },
      {
        name: "Blockchain Explorer",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Blockchain Developer"],
      },
      {
        name: "Cryptocurrency Staking and Yield Farming",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Blockchain Developer"],
      },
      {
        name: "Mining Pool Integration",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Mining Specialist"],
      },
      {
        name: "Wallet Recovery Options",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Mobile App Development",
        manDays: "40-80 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Mobile App Developer", "UI/UX Designer"],
      },
      {
        name: "Smart Contract Development",
        manDays: "40-80 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Blockchain Developer", "Smart Contract Developer"],
      },
      {
        name: "Decentralized Finance (DeFi) Integration",
        manDays: "40-80 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Backend Developer", "DeFi Specialist"],
      },
      {
        name: "Security Audits and Penetration Testing",
        manDays: "Ongoing and may require dedicated resources",
        totalManDays: 80,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "User Support and Help Center",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Customer Support Specialist"],
      },
      {
        name: "Regulatory Compliance",
        manDays: "Ongoing and may require dedicated resources",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Compliance Specialist"],
      },
    ],
  },
  {
    category: "Insurtech",
    features: [
      {
        name: "User Registration and Profile Management",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Insurance Quote Generation",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Policy Purchase and Management",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Claims Submission",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Claims Processing and Verification",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Document Management (Policies, Certificates)",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Premium Payments and Billing",
        manDays: "20-40 man-days",
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Policy Recommendation Engine",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Customer Support and Communication",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Customer Support Specialist"],
      },
      {
        name: "AI-Based Risk Assessment",
        manDays: "40-80 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Data Scientist", "Machine Learning Engineer"],
      },
      {
        name: "Fraud Detection and Prevention",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Security Specialist"],
      },
      {
        name: "Integration with Third-Party Data Providers",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Claims History and Analytics",
        manDays: "20-40 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Mobile App Development",
        manDays: "40-80 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Mobile App Developer", "UI/UX Designer"],
      },
      {
        name: "Insurance Product Customization",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Regulatory Compliance",
        manDays: "Ongoing and may require dedicated resources",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Compliance Specialist"],
      },
      {
        name: "Machine Learning Model Development",
        manDays: "40-80 man-days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Data Scientist", "Machine Learning Engineer"],
      },
      {
        name: "Policy Comparison and Recommendations",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Data Privacy and Security Measures",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Customer Education and Content Creation",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Content Creator"],
      },
    ],
  },
  {
    category: "Personal Finance and Budgeting Platform",
    features: [
      {
        name: "User Registration and Profile Management",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Expense Tracking",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Income Tracking",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Budget Creation and Management",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Transaction Categorization",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Bill Reminder and Payment Tracking",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Financial Goal Setting",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Debt Management and Tracking",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Net Worth Calculation",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Financial Reports and Analytics",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Bank Account Integration",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "API Integration Specialist"],
      },
      {
        name: "Credit Score Monitoring",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Investment Portfolio Tracking",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Data Import/Export",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Mobile App Development",
        manDays: "40-80 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Mobile App Developer", "UI/UX Designer"],
      },
      {
        name: "Expense Analysis and Insights",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
      {
        name: "Customizable Budget Categories",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Financial Education Content",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Content Creator"],
      },
      {
        name: "Security and Data Privacy Measures",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Customer Support and Help Center",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Customer Support Specialist"],
      },
    ],
  },
  {
    category: "Real Estate and Property Technology (PropTech) platform",
    features: [
      {
        name: "Property Listings and Search",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Property Details and Descriptions",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Property Valuation Tools",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
      {
        name: "Virtual Property Tours",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Property History and Transaction Data",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Mortgage Calculator",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Property Alerts and Notifications",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Agent and Broker Profiles",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Booking and Scheduling Property Viewings",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Property Inspection Reports",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Property Financing Options",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Property Legal and Regulatory Information",
        manDays: "15-30 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Legal Specialist"],
      },
      {
        name: "Property Comparison Tools",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Property Management and Tenant Portal",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Neighborhood and Location Information",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Feedback and Review System",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Document Management and E-signatures",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Customer Support and Help Center",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Customer Support Specialist"],
      },
      {
        name: "Integration with Property Data Providers",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Property Investment Analysis Tools",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Financial Analyst"],
      },
    ],
  },
  {
    category: "Open Banking and APIs platform",
    features: [
      {
        name: "API Management Dashboard",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "API Authentication and Security",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Developer Portal",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["UI/UX Designer"],
      },
      {
        name: "API Rate Limiting and Throttling",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "API Versioning and Compatibility",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Data Access Consent Management",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Transaction Data Retrieval",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Payment Initiation APIs",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Account Aggregation",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "User Authentication and Authorization Flow",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Data Enrichment and Categorization",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Data Analyst"],
      },
      {
        name: "Error Handling and Logging",
        manDays: "10-20 man-days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Compliance and Regulatory Integration",
        manDays: "30-60 man-days",
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Compliance Specialist"],
      },
      {
        name: "Webhooks and Event Notifications",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Analytics and Reporting Dashboard",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Data Analyst"],
      },
      {
        name: "Audit Trail and Activity Logs",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Consent Revocation and Management",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Data Privacy and Security Measures",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Developer Support and Documentation",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Technical Writer"],
      },
      {
        name: "Scalability and Load Testing",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["QA Engineer"],
      },
    ],
  },
  {
    category: "Payment Processing and Infrastructure",
    features: [
      {
        name: "Payment Gateway Integration",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Payment Card Processing",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Payment APIs and SDKs",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Cross-Border Payment Solutions",
        manDays: "30-60 man-days",
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Contactless and Mobile Payments",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Subscription Billing",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Payment Reconciliation and Reporting",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Tokenization and Data Security",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Payment Processing Speed and Reliability",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Merchant Account Management",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Fraud Detection and Prevention",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Payment Notifications and Alerts",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "PCI DSS Compliance",
        manDays: "30-60 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Security Specialist"],
      },
      {
        name: "Payment Routing and Settlement",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Dispute Resolution and Chargeback Handling",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Mobile Point-of-Sale (mPOS) Systems",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Real-Time Payment Processing",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Payment Infrastructure Scaling",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Payment Analytics and Insights",
        manDays: "15-30 man-days",
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Data Analyst"],
      },
      {
        name: "Payment Recovery and Retry",
        manDays: "20-40 man-days",
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
    ],
  },
];
export const FintechResources = [
  {
    role: "Backend Developer",
    skills: ["UI/UX Design", "Wireframing", "Prototyping"],
  },
  {
    role: "UI/UX Designer",
    skills: ["UI/UX Design", "Wireframing", "Prototyping"],
  },
  {
    role: "Data Analyst",
    skills: [
      "Data Mining",
      "Statistical Analysis",
      "Machine Learning Algorithms",
      "Python",
      "R",
    ],
  },
  {
    role: "Mobile App Developer",
    skills: ["Swift", "Java", "Kotlin", "React Native", "Flutter"],
  },
  {
    role: "Security Expert",
    skills: ["Security Assessment", "Fraud Detection", "Security Protocols"],
  },
  {
    role: "Blockchain Developer",
    skills: ["Blockchain Development", "Smart Contracts", "Crypto Wallets"],
  },
];
export const FintechTechStack = [
  "Node.js",
  "React.js",
  "React Native",
  "Blockchain (e.g., Ethereum)",
  "PCI DSS Compliance Tools",
  "Machine Learning (ML)",
];
