export const HealthTech = [
  {
    category: "Predictive Analytics Platforms",
    features: [
      {
        name: "Data integration and preprocessing",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python", "Pandas", "SQL"],
      },
      {
        name: "Model development and training",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Python", "Scikit-Learn", "TensorFlow"],
      },
      {
        name: "Model deployment and monitoring",
        manDays: 80,
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Docker", "Kubernetes", "Prometheus"],
      },
      {
        name: "Data visualization and reporting",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["JavaScript", "React", "D3.js"],
      },
      {
        name: "Scalability for handling large datasets",
        manDays: 90,
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
        recommendedStack: ["Apache Spark", "Hadoop", "AWS EMR"],
      },
      {
        name: "Integration with Electronic Health Records (EHR)",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
        recommendedStack: ["HL7", "FHIR", "DICOM"],
      },
      {
        name: "Automated machine learning (AutoML)",
        manDays: 80,
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["AutoML Libraries", "Python", "Jupyter Notebook"],
      },
      {
        name: "Telehealth Integration",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
        recommendedStack: ["Telehealth APIs", "WebRTC", "Video Streaming"],
      },
      {
        name: "Natural Language Processing (NLP)",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "NLP Engineer"],
        recommendedStack: ["Python", "NLTK", "spaCy"],
      },
      {
        name: "Patient Engagement",
        manDays: 70,
        totalManDays: 70,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["JavaScript", "React", "Redux"],
      },
      {
        name: "Reporting and Analytics",
        manDays: 70,
        totalManDays: 70,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: [
          "JavaScript",
          "Data Visualization Libraries",
          "Dashboard Frameworks",
        ],
      },
      {
        name: "Compliance with Healthcare Regulations",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Compliance Expert"],
        recommendedStack: [
          "HIPAA Compliance Toolkit",
          "Regulatory Compliance Frameworks",
        ],
      },
    ],
  },

  {
    category: "Electronic Health Records (EHR) software",
    features: [
      {
        name: "Patient record management",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js", "PostgreSQL, MySQL"],
      },
      {
        name: "Secure data storage",
        manDays: 20,
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js", "AES, RSA", "OAuth, LDAP"],
      },
      {
        name: "Interoperability for data sharing",
        manDays: 10,
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
        recommendedStack: ["Node.js", "HL7 Integration", "FHIR Standards"],
      },
      {
        name: "E-prescribing",
        manDays: 50,
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js", "Surescripts"],
      },
      {
        name: "Clinical decision support",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: [
          "Node.js",
          "Python",
          "IBM Watson",
          "TensorFlow",
          "scikit-learn",
        ],
      },
      {
        name: "Patient portal access",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["SMART on FHIR", "oAuth"],
      },
    ],
  },
  {
    category: "Medical Imaging software",
    features: [
      {
        name: "DICOM support for image standardization",
        manDays: 50,
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer", "Imaging Specialist"],
        recommendedStack: ["Python", "DICOM Libraries", "Image Processing"],
      },
      {
        name: "Image viewing and manipulation tools",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python", "UI Frameworks"],
      },
      {
        name: "3D reconstruction capabilities",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer", "3D Graphics Developer"],
        recommendedStack: ["Python", "3D Rendering Engines"],
      },
      {
        name: "Integration with PACS (Picture Archiving and Communication System)",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
        recommendedStack: ["Python", "Healthcare Data Exchange"],
      },
    ],
  },
  {
    category: "Telemedicine software",
    features: [
      {
        name: "Video conferencing for remote consultations",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Video Streaming Expert"],
        recommendedStack: ["Python", "WebRTC", "Video Conferencing Platforms"],
      },
      {
        name: "Secure patient data transmission",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Security Specialist"],
        recommendedStack: [
          "Python",
          "Encryption Protocols",
          "Secure Data Transmission Tools",
        ],
      },
      {
        name: "Appointment scheduling",
        manDays: 50,
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer", "Appointment Scheduling Specialist"],
        recommendedStack: [
          "Python",
          "Appointment Scheduling Systems",
          "Calendar APIs",
        ],
      },
      {
        name: "Prescription management",
        manDays: 40,
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python", "Pharmacy Integration APIs"],
      },
      {
        name: "Telehealth reimbursement support",
        manDays: 40,
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
        recommendedStack: ["Python", "Insurance Integration APIs"],
      },
    ],
  },
  {
    category: "Health and Wellness apps",
    features: [
      {
        name: "Fitness tracking features",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React native", "Flutter", "Health Data APIs"],
      },
      {
        name: "Nutritional guidance and meal planning",
        manDays: 50,
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React native", "Meal Planning Algorithms"],
      },
      {
        name: "Health goal setting",
        manDays: 20,
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React native", "Flutter"],
      },
      {
        name: "Social sharing",
        manDays: 30,
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React native", "Flutter"],
      },
    ],
  },
  {
    category: "Hospital Information Systems (HIS)",
    features: [
      {
        name: "Patient registration",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python", "Data Validation Tools"],
      },
      {
        name: "Billing and financial management",
        manDays: 130,
        totalManDays: 130,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
        recommendedStack: ["Python", "Financial Analytics Tools"],
      },
      {
        name: "Inventory management",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python", "Barcode Scanning Integration"],
      },
      {
        name: "Electronic health records integration",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python"],
      },
      {
        name: "Reporting and analytics",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python"],
      },
    ],
  },
  {
    category: "Healthcare Analytics software",
    features: [
      {
        name: "Data aggregation and cleansing",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python"],
      },
      {
        name: "Data visualization tools",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python"],
      },
      {
        name: "Predictive analytics for patient outcomes",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Python"],
      },
      {
        name: "Performance monitoring and benchmarking",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python"],
      },
    ],
  },
  {
    category: "Practice Management software",
    features: [
      {
        name: "Appointment scheduling and reminders",
        manDays: 50,
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python"],
      },
      {
        name: "Billing and invoicing",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Patient demographics management",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Reporting and analytics",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Integration with EHR systems",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
    ],
  },
  {
    category: "Pharmacy Management software",
    features: [
      {
        name: "Prescription processing and labeling",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Inventory tracking and management",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Drug interaction alerts",
        manDays: 50,
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Insurance claims processing",
        manDays: 30,
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Patient medication profiles",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
    ],
  },
  {
    category: "Medical Billing and Coding software",
    features: [
      {
        name: "Policy administration",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Claims processing and adjudication",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Member enrollment and management",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Premium billing and payment processing",
        manDays: 20,
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Regulatory compliance tools",
        manDays: 30,
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
    ],
  },
  {
    category: "Health Insurance Management software",
    features: [
      {
        name: "Code lookup and selection assistance",
        manDays: 40,
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Claims submission and tracking",
        manDays: 80,
        totalManDays: 80,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Revenue cycle management",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Compliance with healthcare coding standards (e.g., ICD-10, CPT)",
        manDays: 30,
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Reporting and analytics for billing performance",
        manDays: 40,
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
    ],
  },
];
