export const HealthTech = [
  {
    category: "Predictive Analytics Platforms",
    features: [
      {
        name: "Data integration and preprocessing",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
      {
        name: "Model development and training",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Model deployment and monitoring",
        manDays: 80,
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Data visualization and reporting",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Scalability for handling large datasets",
        manDays: 90,
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
      },
      {
        name: "Integration with Electronic Health Records (EHR)",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
      },
      {
        name: "Automated machine learning (AutoML)",
        manDays: 80,
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Telehealth Integration",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
      },
      {
        name: "Natural Language Processing (NLP)",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "NLP Engineer"],
      },
      {
        name: "Patient Engagement",
        manDays: 70,
        totalManDays: 70,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Reporting and Analytics",
        manDays: 70,
        totalManDays: 70,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Compliance with Healthcare Regulations",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Compliance Expert"],
      },
    ],
  },
  {
    category: "Electronic Health Records (EHR) software",
    features: [
      {
        name: "Patient record management",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Secure data storage",
        manDays: 20,
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Interoperability for data sharing",
        manDays: 10,
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Engineer"],
      },
      {
        name: "E-prescribing",
        manDays: 50,
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Clinical decision support",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Patient portal access",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
    ],
  },
  {
    category: "Medical Imaging software",
    features: [
      {
        name: "DICOM support for image standardization",
        manDays: 50,
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer", "Imaging Specialist"],
      },
      {
        name: "Image viewing and manipulation tools",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "3D reconstruction capabilities",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer", "3D Graphics Developer"],
      },
      {
        name: "Integration with PACS (Picture Archiving and Communication System)",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
      },
    ],
  },
  {
    category: "Telemedicine software",
    features: [
      {
        name: "Video conferencing for remote consultations",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Video Streaming Expert"],
      },
      {
        name: "Secure patient data transmission",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Security Specialist"],
      },
      {
        name: "Appointment scheduling",
        manDays: 50,
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer", "Appointment Scheduling Specialist"],
      },
      {
        name: "Prescription management",
        manDays: 40,
        totalManDays: 40,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Telehealth reimbursement support",
        manDays: 40,
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
    ],
  },
  {
    category: "Health and Wellness apps",
    features: [
      {
        name: "Fitness tracking features",
        manDays: 60,
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Nutritional guidance and meal planning",
        manDays: 50,
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Health goal setting",
        manDays: 20,
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Social sharing",
        manDays: 30,
        totalManDays: 30,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
    ],
  },
  {
    category: "Hospital Information Systems (HIS)",
    features: [
      {
        name: "Patient registration",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
      {
        name: "Billing and financial management",
        manDays: 130,
        totalManDays: 130,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Inventory management",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Inventory Management Specialist"],
      },
      {
        name: "Electronic health records integration",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
      },
      {
        name: "Reporting and analytics",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
    ],
  },
  {
    category: "Healthcare Analytics software",
    features: [
      {
        name: "Data aggregation and cleansing",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
      {
        name: "Data visualization tools",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Predictive analytics for patient outcomes",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
      },
      {
        name: "Performance monitoring and benchmarking",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
    ],
  },
  {
    category: "Practice Management software",
    features: [
      {
        name: "Appointment scheduling and reminders",
        manDays: 50,
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer", "Appointment Scheduling Specialist"],
      },
      {
        name: "Billing and invoicing",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Patient demographics management",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
      {
        name: "Reporting and analytics",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
      {
        name: "Integration with EHR systems",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
      },
    ],
  },
  {
    category: "Pharmacy Management software",
    features: [
      {
        name: "Prescription processing and labeling",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Pharmacy Specialist"],
      },
      {
        name: "Inventory tracking and management",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Inventory Management Specialist"],
      },
      {
        name: "Drug interaction alerts",
        manDays: 50,
        totalManDays: 50,
        numResources: 2,
        devRequired: ["Backend Developer", "Pharmacy Specialist"],
      },
      {
        name: "Insurance claims processing",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Patient medication profiles",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Pharmacy Specialist"],
      },
    ],
  },
  {
    category: "Medical Billing and Coding software",
    features: [
      {
        name: "Policy administration",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer", "Billing Specialist"],
      },
      {
        name: "Claims processing and adjudication",
        manDays: 140,
        totalManDays: 140,
        numResources: 2,
        devRequired: ["Backend Developer", "Claims Specialist"],
      },
      {
        name: "Member enrollment and management",
        manDays: 60,
        totalManDays: 60,
        numResources: 2,
        devRequired: ["Backend Developer", "Member Management Specialist"],
      },
      {
        name: "Premium billing and payment processing",
        manDays: 20,
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Regulatory compliance tools",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Compliance Specialist"],
      },
    ],
  },
  {
    category: "Health Insurance Management software",
    features: [
      {
        name: "Code lookup and selection assistance",
        manDays: 40,
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Coding Specialist"],
      },
      {
        name: "Claims submission and tracking",
        manDays: 80,
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Backend Developer", "Claims Specialist"],
      },
      {
        name: "Revenue cycle management",
        manDays: 100,
        totalManDays: 100,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Compliance with healthcare coding standards (e.g., ICD-10, CPT)",
        manDays: 30,
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Coding Specialist"],
      },
      {
        name: "Reporting and analytics for billing performance",
        manDays: 40,
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
    ],
  },
];
export const HealthCareResources = [
  {
    role: "Backend Developer",
    skills: ["Python", "Java", "Node.js", "Database Management"],
  },
  {
    role: "Frontend Developer",
    skills: ["HTML", "CSS", "JavaScript", "UI/UX Design"],
  },
  {
    role: "Data Analyst",
    skills: ["Data Analysis", "SQL", "Data Visualization"],
  },
  {
    role: "Data Scientist",
    skills: ["Machine Learning", "Python", "R", "Statistical Analysis"],
  },
  {
    role: "Data Engineer",
    skills: [
      "Big Data Technologies",
      "ETL Processes",
      "Database Administration",
    ],
  },
  {
    role: "NLP Engineer",
    skills: ["Natural Language Processing", "Python", "NLP Libraries"],
  },
  {
    role: "Compliance Expert",
    skills: ["Healthcare Regulations", "Legal Compliance"],
  },
];

export const HealthCareTechStack = [
  "Python",
  "Java",
  "Node.js",
  "Database Management",
  "HTML",
  "CSS",
  "JavaScript",
  "Data Analysis",
  "SQL",
  "Machine Learning",
  "Big Data Technologies",
  "Natural Language Processing",
  // Add more technologies as needed.
];