export const hospitality = [
  {
    category: "Online Booking System",
    features: [
      {
        name: "Real-time reservation availability",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js","Real-time Database"],
      },
      {
        name: "Pricing and rate management",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Confirmation and booking notifications",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Property Management System (PMS)",
    features: [
      {
        name: "Check-ins and check-outs management",
        manDays: "20-40 days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Room assignments and availability",
        manDays: "20-40 days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Billing and guest profiles",
        manDays: "20-40 days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Integration with other systems",
        manDays: "20-40 days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Point of Sale (POS) System",
    features: [
      {
        name: "Order entry and processing",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Payment processing",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Inventory management",
        manDays: "12-24 days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Inventory Management",
    features: [
      {
        name: "Inventory level management",
        manDays: "8-16 days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Restocking automation",
        manDays: "8-16 days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Wastage reduction",
        manDays: "8-16 days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Guest Services Portal",
    features: [
      {
        name: "Guest information and services",
        manDays: "8-16 days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Service request functionality",
        manDays: "8-16 days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Customer Relationship Management (CRM)",
    features: [
      {
        name: "Guest data management",
        manDays: "12-24 days",
        totalManDays: 22,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Personalization of services",
        manDays: "12-24 days",
        totalManDays: 22,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Housekeeping Management",
    features: [
      {
        name: "Housekeeping task management",
        manDays: "8-16 days",
        totalManDays: 14,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Room cleaning schedules",
        manDays: "8-16 days",
        totalManDays: 14,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Maintenance request handling",
        manDays: "8-16 days",
        totalManDays: 14,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Reservation Management",
    features: [
      {
        name: "Tracking and modification of bookings",
        manDays: "8-16 days",
        totalManDays: 16,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
];