export const MachineLearning = [
  {
    category: "Predictive Maintenance Solution",
    features: [
      {
        name: "Sensor data integration",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: ["AWS IoT", "TensorFlow"],
      },
      {
        name: "Machine learning models for failure prediction",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: ["PyTorch", "Apache Spark"],
      },
      {
        name: "Maintenance scheduling optimization",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: ["Scikit-Optimize", "Tableau"],
      },
      {
        name: "Real-time monitoring and alerts",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: ["Apache Kafka", "Slack"],
      },
    ],
  },
  {
    category: "Churn Prediction and Customer Retention System",
    features: [
      {
        name: "Customer data analysis",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python Pandas", "Tableau"],
      },
      {
        name: "Churn prediction models",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["scikit-learn", "Databricks"],
      },
      {
        name: "Customer engagement recommendations",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["TensorFlow", "Apache Mahout"],
      },
      {
        name: "Segmentation for targeted marketing",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Scikit-Seg", "HubSpot"],
      },
    ],
  },
  {
    category: "Recommendation System",
    features: [
      {
        name: "User profiling and behavior analysis",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python Pandas", "Mixpanel"],
      },
      {
        name: "Collaborative filtering or content-based recommendation algorithms",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["PyTorch", "Firebase"],
      },
      {
        name: "Real-time content updates",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Apache Kafka", "Optimizely"],
      },
      {
        name: "A/B testing and performance analytics",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Google Optimize", "Google Analytics"],
      },
    ],
  },
  {
    category: "Natural Language Processing (NLP) Text Classification",
    features: [
      {
        name: "Text preprocessing and feature extraction",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "NLP Engineer"],
        recommendedStack: ["NNLTK", "TfidfVectorizer"],
      },
      {
        name: "Supervised learning models (e.g., Naive Bayes, SVM, or deep learning)",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["TensorFlow", "Keras"],
      },
      {
        name: "Sentiment analysis or topic classification",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "NLP Engineer"],
        recommendedStack: ["spaCy", "Apache Nifi"],
      },
      {
        name: "Real-time text processing and prediction",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "NLP Engineer"],
        recommendedStack: ["Apache Kafka", "Real-time Prediction Engines"],
      },
    ],
  },
  {
    category: "Credit Scoring and Risk Assessment Model",
    features: [
      {
        name: "Credit applicant data collection",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Python Requests", "Hadoop"],
      },
      {
        name: "Credit scoring models",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["scikit-learn", "Predictive Analytics Tools"],
      },
      {
        name: "Risk assessment and credit limit recommendations",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["PyTorch", "RiskWatch"],
      },
      {
        name: "Regulatory compliance checks",
        manDays: "40 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: [
          "Compliance Checking Tools",
          "Regulatory Reporting Software",
        ],
      },
    ],
  },
  {
    category: "Anomaly Detection System",
    features: [
      {
        name: "Data preprocessing and feature engineering",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Pandas", "scikit-learn"],
      },
      {
        name: "Unsupervised anomaly detection models (e.g., Isolation Forest, Autoencoders)",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["TensorFlow", "PyOD"],
      },
      {
        name: "Real-time anomaly alerts and reporting",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Apache Kafka", "Grafana"],
      },
      {
        name: "Model retraining and adaptation",
        manDays: "30 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Scientist"],
        recommendedStack: ["Kubeflow", "Continuous Monitoring Systems"],
      },
    ],
  },
  {
    category: "Image Recognition and Tagging System",
    features: [
      {
        name: "Deep learning-based image analysis",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: ["TensorFlow", "OpenCV"],
      },
      {
        name: "Object recognition and tagging",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: ["Object Detection Models", "Image Tagging Tools"],
      },
      {
        name: "Image metadata generation",
        manDays: "24 Man Days",
        totalManDays: 24,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: [
          "Image Metadata Tools",
          "Content Management Systems",
        ],
      },
      {
        name: "Integration with content management systems",
        manDays: "22 Man Days",
        totalManDays: 22,
        numResources: 2,
        devRequired: ["Backend Developer", "Machine Learning Engineer"],
        recommendedStack: [
          "CMS Integration Plugins",
          "APIs for CMS Integration",
        ],
      },
    ],
  },
];