export const RealEstate = [
  {
    category: "CMS",
    features: [
      {
        name: "User Profile",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python Django", "UI/UX"],
      },
      {
        name: "Property Listing",
        manDays: "10 + 10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Property Submission",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "CRM provider integration",
        manDays: "5 + 15 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
        recommendedStack: ["Node.js", "CRM API"],
      },
      {
        name: "Data Providers Integration",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Payment Integration",
        manDays: "5 + 15 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
        recommendedStack: ["Node.js", "Payment Gateway API"],
      },
      {
        name: "Lead Generation Integration",
        manDays: "5 + 15 Man Days",
        totalManDays: 25,
        numResources: 2,
        devRequired: ["Backend Developer", "Marketing Specialist"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "API Integration",
        manDays: "0 + 20 Man Days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Responsiveness for all Devices",
        manDays: "15 + 0 Man Days",
        totalManDays: 15,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["UI/UX"],
      },
      {
        name: "Map Integration",
        manDays: "10 + 20 Man Days",
        totalManDays: 45,
        numResources: 2,
        devRequired: ["Backend Developer", "Map Integration Specialist"],
        recommendedStack: ["Node.js", "Google Maps API"],
      },
      {
        name: "Messaging and Notifications",
        manDays: "15 + 20 Man Days",
        totalManDays: 35,
        numResources: 2,
        devRequired: ["Backend Developer", "Notification Specialist"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Advance Search and Filters",
        manDays: "5 + 15 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Booking and Scheduling",
        manDays: "10 + 15 Man Days",
        totalManDays: 25,
        numResources: 2,
        devRequired: ["Backend Developer", "Scheduling Specialist"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Admin and Agent Panels",
        manDays: "15 + 30 Man Days",
        totalManDays: 45,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Customize design page for properties",
        manDays: "10 + 10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Analytics and Reporting",
        manDays: "10 + 15 Man Days",
        totalManDays: 25,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
        recommendedStack: ["Node.js"],
      },
    ],
  },
  {
    category: "Interactive Wall",
    features: [
      {
        name: "Property listing",
        manDays: "3 + 2 Man Days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Property Showcase",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive Floor Plans",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive Units, Leasing Module for individual units",
        manDays: "10 + 3 days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive property Amenities",
        manDays: "3 + 2 days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "360-Degree Virtual Tours",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Neighborhood Maps Integrations",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js", "Google Maps API"],
      },
      {
        name: "Property Search and Filters",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Property Details",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive Maps",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js", "Google Maps API"],
      },
      {
        name: "Save Favorites",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Email Favorite Items",
        manDays: "5 + 3 Man Days",
        totalManDays: 8,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Offline Mode",
        manDays: "20 + 0 Man Days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
    ],
  },
  {
    category: "Mobile Application",
    features: [
      {
        name: "Property listing",
        manDays: "3 + 2 Man Days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Property Showcase",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Interactive Floor Plans",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Interactive Units, Leasing Module for individual units",
        manDays: "10 + 3 days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Interactive property Amenities",
        manDays: "3 + 2 days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "360-Degree Virtual Tours",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Neighborhood Maps Integrations",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native", "Google Maps API"],
      },
      {
        name: "Property Search and Filters",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Property Details",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Interactive Maps",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native", "Google Maps API"],
      },
      {
        name: "Save Favorites",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
      {
        name: "Email Favorite Items",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
        recommendedStack: ["React Native"],
      },
    ],
  },
  {
    category: "Interactive Embedded Web Application",
    features: [
      {
        name: "Property listing",
        manDays: "3 + 2 Man Days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Property Showcase",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive Floor Plans",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive Units, Leasing Module for individual units",
        manDays: "10 + 3 days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive property Amenities",
        manDays: "3 + 2 days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "360-Degree Virtual Tours",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Neighborhood Maps Integrations",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js", "Google Maps API"],
      },
      {
        name: "Floorplates View",
        manDays: "10 + 5 Man Days",
        totalManDays: 15,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Sitemap View",
        manDays: "5 + 5 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Interactive Maps",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js", "Google Maps API"],
      },
      {
        name: "Share Favorites",
        manDays: "5 + 3 Man Days",
        totalManDays: 8,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Save Favorites",
        manDays: "10 + 4 Man Days",
        totalManDays: 14,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
      {
        name: "Email Favorite Items",
        manDays: "3 + 6 Man Days",
        totalManDays: 9,
        numResources: 1,
        devRequired: ["Frontend Developer"],
        recommendedStack: ["React.js"],
      },
    ],
  },
];
