export const RealEstate = [
  {
    category: "CMS",
    features: [
      {
        name: "User Profile",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Property Listing",
        manDays: "10 + 10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Property Submission",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "CRM provider integration",
        manDays: "5 + 15 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
      },
      {
        name: "Data Providers Integration",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Backend Developer", "Integration Specialist"],
      },
      {
        name: "Payment Integration",
        manDays: "5 + 15 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "Financial Specialist"],
      },
      {
        name: "Lead Generation Integration",
        manDays: "5 + 15 Man Days",
        totalManDays: 25,
        numResources: 2,
        devRequired: ["Backend Developer", "Marketing Specialist"],
      },
      {
        name: "API Integration",
        manDays: "0 + 20 Man Days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
      },
      {
        name: "Responsiveness for all Devices",
        manDays: "15 + 0 Man Days",
        totalManDays: 15,
        numResources: 1,
        devRequired: ["UI/UX Designer"],
      },
      {
        name: "Map Integration",
        manDays: "10 + 20 Man Days",
        totalManDays: 45,
        numResources: 2,
        devRequired: ["Backend Developer", "Map Integration Specialist"],
      },
      {
        name: "Messaging and Notifications",
        manDays: "15 + 20 Man Days",
        totalManDays: 35,
        numResources: 2,
        devRequired: ["Backend Developer", "Notification Specialist"],
      },
      {
        name: "Advance Search and Filters",
        manDays: "5 + 15 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Booking and Scheduling",
        manDays: "10 + 15 Man Days",
        totalManDays: 25,
        numResources: 2,
        devRequired: ["Backend Developer", "Scheduling Specialist"],
      },
      {
        name: "Admin and Agent Panels",
        manDays: "15 + 30 Man Days",
        totalManDays: 45,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Customize design page for properties",
        manDays: "10 + 10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Backend Developer", "UI/UX Designer"],
      },
      {
        name: "Analytics and Reporting",
        manDays: "10 + 15 Man Days",
        totalManDays: 25,
        numResources: 2,
        devRequired: ["Backend Developer", "Data Analyst"],
      },
    ],
  },
  {
    category: "Interactive Wall",
    features: [
      {
        name: "Property listing",
        manDays: "3 + 2 Man Days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Property Showcase",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive Floor Plans",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive Units, Leasing Module for individual units",
        manDays: "10 + 3 days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive property Amenities",
        manDays: "3 + 2 days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "360-Degree Virtual Tours",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Neighborhood Maps Integrations",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Property Search and Filters",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Property Details",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive Maps",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Save Favorites",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Email Favorite Items",
        manDays: "5 + 3 Man Days",
        totalManDays: 8,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Offline Mode",
        manDays: "20 + 0 Man Days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
    ],
  },
  {
    category: "Mobile Application",
    features: [
      {
        name: "Property listing",
        manDays: "3 + 2 Man Days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Property Showcase",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Interactive Floor Plans",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Interactive Units, Leasing Module for individual units",
        manDays: "10 + 3 days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Interactive property Amenities",
        manDays: "3 + 2 days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "360-Degree Virtual Tours",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Neighborhood Maps Integrations",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Property Search and Filters",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Property Details",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Interactive Maps",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Save Favorites",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
      {
        name: "Email Favorite Items",
        manDays: "5 + 10 Man Days",
        totalManDays: 15,
        numResources: 1,
        devRequired: ["Mobile App Developer"],
      },
    ],
  },
  {
    category: "Interactive Embedded Web Application",
    features: [
      {
        name: "Property listing",
        manDays: "3 + 2 Man Days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Property Showcase",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive Floor Plans",
        manDays: "10 + 2 Man Days",
        totalManDays: 12,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive Units, Leasing Module for individual units",
        manDays: "10 + 3 days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive property Amenities",
        manDays: "3 + 2 days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "360-Degree Virtual Tours",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Neighborhood Maps Integrations",
        manDays: "5 + 2 Man Days",
        totalManDays: 7,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Floorplates View",
        manDays: "10 + 5 Man Days",
        totalManDays: 15,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Sitemap View",
        manDays: "5 + 5 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Interactive Maps",
        manDays: "10 + 3 Man Days",
        totalManDays: 13,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Share Favorites",
        manDays: "5 + 3 Man Days",
        totalManDays: 8,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Save Favorites",
        manDays: "10 + 4 Man Days",
        totalManDays: 14,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
      {
        name: "Email Favorite Items",
        manDays: "3 + 6 Man Days",
        totalManDays: 9,
        numResources: 1,
        devRequired: ["Frontend Developer"],
      },
    ],
  },
];
export const RealEstateResources = [
  {
    role: "Backend Developer",
    description: "Responsible for server-side development and integration.",
  },
  {
    role: "UI/UX Designer",
    description:
        "Responsible for designing user interfaces and user experience.",
  },
  {
    role: "Integration Specialist",
    description: "Specializes in integrating third-party services and APIs.",
  },
  {
    role: "Financial Specialist",
    description: "Manages financial aspects and payment integration.",
  },
  {
    role: "Marketing Specialist",
    description: "Handles lead generation and marketing integration.",
  },
  {
    role: "Data Analyst",
    description: "Analyzes data for reporting and analytics features.",
  },
  {
    role: "Scheduling Specialist",
    description: "Manages booking and scheduling functionality.",
  },
  {
    role: "Notification Specialist",
    description: "Handles messaging and notification features.",
  },
  {
    role: "Map Integration Specialist",
    description: "Specializes in integrating map-related functionality.",
  },
  {
    role: "Mobile App Developer",
    description: "Develops mobile applications for property listings.",
  },
  {
    role: "Frontend Developer",
    description: "Responsible for frontend development of web applications.",
  },
];

export const RealEstateTechStack = [
  {
    technology: "Node.js",
    description: "Backend server development.",
  },
  {
    technology: "React.js",
    description: "Frontend web application development.",
  },
  {
    technology: "React Native",
    description: "Development of mobile applications.",
  },
  {
    technology: "Google Maps API",
    description: "Integration of map-related features.",
  },
  {
    technology: "Payment Gateway API",
    description: "Integration of payment processing.",
  },
  {
    technology: "CRM API",
    description: "Integration with CRM providers.",
  },
];