export const TransportManagementSystem = [
  {
    category: "Carrier Integration (for 1 Carrier)",
    features: [
      {
        name: "Setup customer's account to integrate the APIs",
        manDays: "2 Man Days",
        totalManDays: 2,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["API Integration", "OAuth"],
      },
      {
        name: "Carriers quote generation",
        manDays: "10 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Carriers shipment",
        manDays: "25 Man Days",
        totalManDays: 25,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Carriers tracking",
        manDays: "20 Man Days",
        totalManDays: 20,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Carriers pickup",
        manDays: "10 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
      {
        name: "Carriers label generation",
        manDays: "25 Man Days",
        totalManDays: 25,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Node.js"],
      },
    ],
  },
  {
    category: "ERP Integration",
    features: [
      {
        name: "Setup customer's account to integrate the APIs",
        manDays: "2 Man Days",
        totalManDays: 2,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: [
          "API Integration (e.g., SOAP)",
          "ERP API Documentation",
        ],
      },
      {
        name: "ERP order fetching + mapping",
        manDays: "10 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python Django"],
      },
      {
        name: "ERP order processing",
        manDays: "10 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python Django"],
      },
      {
        name: "ERP order status update",
        manDays: "5 Man Days",
        totalManDays: 5,
        numResources: 1,
        devRequired: ["Backend Developer"],
        recommendedStack: ["Python Django"],
      },
    ],
  },
  {
    category: "Web application",
    features: [
      {
        name: "Multi-tenant",
        manDays: "15+15 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Express.js"],
      },
      {
        name: "Reports (5-20)",
        manDays: "15+15 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Express.js"],
      },
      {
        name: "Events and alerts",
        manDays: "15+15 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Express.js"],
      },
      {
        name: "Quote lookup",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Shipment processing page",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Shipment page integration + development",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "User management",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Tracking page implementation",
        manDays: "10+5 Man Days",
        totalManDays: 15,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Pickup page implementation",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Multiple themes",
        manDays: "25+5 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Batch shipment processing (BE + FE)",
        manDays: "30+60 Man Days",
        totalManDays: 90,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Shipment labels generation (different sizes and dimensions)",
        manDays: "15+15 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Reorder shipment",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Cancel shipment",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Order Management",
        manDays: "20+20 Man Days",
        totalManDays: 40,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "ERP order mapping and lookup",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "ERP order processing page",
        manDays: "5+5 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "ERP integration page",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
      {
        name: "Reports and Alerts",
        manDays: "10+10 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Frontend Developer", "Backend Developer"],
        recommendedStack: ["React.js", "Node.js"],
      },
    ],
  },
  {
    category: "Client agent applications",
    features: [
      {
        name: "Label printing setup + application",
        manDays: "60 Man Days",
        totalManDays: 60,
        numResources: 1,
        devRequired: ["Desktop App Developer"],
        recommendedStack: [".Net"],
      },
      {
        name: "Weight scale setup + application",
        manDays: "50 Man Days",
        totalManDays: 50,
        numResources: 1,
        devRequired: ["Desktop App Developer"],
        recommendedStack: [".Net"],
      },
    ],
  },
  {
    category: "Mobile application",
    features: [
      {
        name: "Reporting",
        manDays: "25+5 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Mobile App Developer", "Backend Developer"],
        recommendedStack: ["React native", "Node.js"],
      },
      {
        name: "Alerting",
        manDays: "15+5 Man Days",
        totalManDays: 20,
        numResources: 2,
        devRequired: ["Mobile App Developer", "Backend Developer"],
        recommendedStack: ["React native", "Node.js"],
      },
      {
        name: "Order Management",
        manDays: "25+5 Man Days",
        totalManDays: 30,
        numResources: 2,
        devRequired: ["Mobile App Developer", "Backend Developer"],
        recommendedStack: ["React native", "Node.js"],
      },
      {
        name: "All other features available on the web application",
        manDays: "60+20 Man Days",
        totalManDays: 80,
        numResources: 2,
        devRequired: ["Mobile App Developer", "Backend Developer"],
        recommendedStack: ["React native", "Node.js"],
      },
    ],
  },
];
