export const VirtualReality = [
  {
    category: "VR Training Simulator",
    features: [
      {
        name: "Immersive VR environments",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["Unity3D", "Unreal Engine", "Oculus SDK"],
      },
      {
        name: "Realistic 3D models and simulations",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["Blender", "Maya", "3ds Max"],
      },
      {
        name: "Interactive training modules",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["C# Programming", "VR Interaction Frameworks"],
      },
      {
        name: "Scenario-based learning",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["Scenario Authoring Tools", "Decision Trees"],
      },
    ],
  },
  {
    category: "VR Gaming Experience",
    features: [
      {
        name: "High-quality 3D graphics and animations",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["Unity3D", "Unreal Engine", "CryEngine"],
      },
      {
        name: "Immersive game worlds",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["VR Physics Engines", "Game Design Principles"],
      },
      {
        name: "Motion tracking and hand controllers",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["VR Input SDKs", "Gesture Recognition"],
      },
      {
        name: "Multiplayer and social interaction",
        manDays: "160 Man Days",
        totalManDays: 160,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["Network Multiplayer Frameworks", "Social VR SDKs"],
      },
    ],
  },
  {
    category: "VR Architectural Visualization",
    features: [
      {
        name: "Realistic 3D building models",
        manDays: "100 Man Days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["3D Artist", "Unity Developer"],
        recommendedStack: ["3D Modeling Software", "Architectural CAD Tools"],
      },
      {
        name: "Virtual walkthroughs",
        manDays: "100 Man Days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["3D Artist", "Unity Developer"],
        recommendedStack: [
          "Unity3D",
          "Unreal Engine",
          "VR Visualization Tools",
        ],
      },
      {
        name: "Customization and design options",
        manDays: "100 Man Days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["3D Artist", "Unity Developer"],
        recommendedStack: ["UI/UX Design Tools", "User Customization Features"],
      },
      {
        name: "Integration with architectural software",
        manDays: "100 Man Days",
        totalManDays: 100,
        numResources: 2,
        devRequired: ["3D Artist", "Unity Developer"],
        recommendedStack: [
          "BIM Software Integration",
          "Data Exchange Standards",
        ],
      },
    ],
  },
  {
    category: "VR Healthcare and Therapy Applications",
    features: [
      {
        name: "Therapeutic VR experiences",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["Medical Expert", "Unity Developer", "VR Designer"],
        recommendedStack: ["Medical VR Libraries", "Healthcare Protocols"],
      },
      {
        name: "Pain management and rehabilitation modules",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["Medical Expert", "Unity Developer", "VR Designer"],
        recommendedStack: [
          "Physical Therapy Algorithms",
          "Patient Progress Tracking",
        ],
      },
      {
        name: "Customized patient treatments",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["Medical Expert", "Unity Developer", "VR Designer"],
        recommendedStack: [
          "Treatment Planning Tools",
          "Patient Data Management",
        ],
      },
      {
        name: "Progress tracking and reporting",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["Medical Expert", "Unity Developer", "VR Designer"],
        recommendedStack: [
          "Health Data Analytics",
          "Medical Reporting Systems",
        ],
      },
    ],
  },
  {
    category: "VR Museum or Art Gallery",
    features: [
      {
        name: "Virtual museum or gallery spaces",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["3D Art Assets", "VR Exhibition Software"],
      },
      {
        name: "High-resolution 3D art and artifact models",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["3D Scanning Technology", "Art Gallery Software"],
      },
      {
        name: "Audio guides and commentary",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["Audio Tour Integration", "Narration Scripting"],
      },
      {
        name: "Educational content and tours",
        manDays: "150 Man Days",
        totalManDays: 150,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: [
          "Educational VR Modules",
          "Interactive Learning Tools",
        ],
      },
    ],
  },
  {
    category: "VR Product Prototyping and Design",
    features: [
      {
        name: "VR-based 3D modeling and prototyping",
        manDays: "170 Man Days",
        totalManDays: 170,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["CAD Integration", "Product Simulation Tools"],
      },
      {
        name: "Collaboration tools for design teams",
        manDays: "170 Man Days",
        totalManDays: 170,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: [
          "Team Collaboration Platforms",
          "Design Review Tools",
        ],
      },
      {
        name: "Real-time design modifications",
        manDays: "170 Man Days",
        totalManDays: 170,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["Live Design Editing", "Design Feedback Systems"],
      },
      {
        name: "Integration with CAD software",
        manDays: "170 Man Days",
        totalManDays: 170,
        numResources: 3,
        devRequired: ["3D Artist", "Unity Developer", "VR Designer"],
        recommendedStack: ["CAD File Compatibility", "CAD-to-VR Plugins"],
      },
    ],
  },
];
