export const WayFinding = [
  {
    category: "CMS",
    features: [
      {
        name: "Indoor Maps on property blueprints",
        manDays: "7 + 3 Man Days",
        totalManDays: 10,
        numResources: 1,
        devRequired: "Backend Developer",
        recommendedStack: ["Python Django"],
      },
      {
        name: "Outdoor Maps via Google Maps",
        manDays: "2 + 2 Man Days",
        totalManDays: 4,
        numResources: 1,
        devRequired: "Backend Developer",
        recommendedStack: ["Python Django"],
      },
      {
        name: "Navigation and Directions via Google Maps",
        manDays: "2 + 2 Man Days",
        totalManDays: 4,
        numResources: 1,
        devRequired: "Backend Developer",
        recommendedStack: ["Google Maps API", "Navigation SDKs"],
      },
      {
        name: "Search Functionality",
        manDays: "3 + 5 Man Days",
        totalManDays: 8,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
        recommendedStack: ["Python Django", "UI/UX Design Tools"],
      },
      {
        name: "Points of Interest (POIs)",
        manDays: "7 + 5 Man Days",
        totalManDays: 12,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
        recommendedStack: ["Python Django", "UI/UX Design Tools"],
      },
      {
        name: "User Analytics",
        manDays: "6 + 4 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: "Backend Developer, Data Analyst",
        recommendedStack: ["Python Django", "Analytics Platforms"],
      },
    ],
  },
  {
    category: "Mobile Application",
    features: [
      {
        name: "Indoor Maps on property blueprints",
        manDays: "7 + 3 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
        recommendedStack: ["Python Django", "React native"],
      },
      {
        name: "Outdoor Maps via Google Maps",
        manDays: "2 + 2 Man Days",
        totalManDays: 4,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
        recommendedStack: ["Python Django", "React native"],
      },
      {
        name: "Navigation and Directions via Google Maps",
        manDays: "2 + 2 Man Days",
        totalManDays: 4,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
        recommendedStack: ["Python Django", "React native"],
      },
      {
        name: "Points of Interest (POIs)",
        manDays: "7 + 5 Man Days",
        totalManDays: 12,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
        recommendedStack: ["Python Django", "React native"],
      },
      {
        name: "User Analytics",
        manDays: "6 + 4 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: "Backend Developer, Data Analyst",
        recommendedStack: ["Python Django", "Analytics Platforms"],
      },
      {
        name: "Search Functionality",
        manDays: "3 + 5 Man Days",
        totalManDays: 8,
        numResources: 2,
        devRequired: "Backend Developer, UI/UX Designer",
        recommendedStack: ["Python Django", "UI/UX Design Tools"],
      },
      {
        name: "Stop to Stop Indoor Navigation",
        manDays: "7 + 3 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
        recommendedStack: ["Python Django", "React native"],
      },
      {
        name: "Indoor user location through scanning QR codes",
        manDays: "6 + 4 Man Days",
        totalManDays: 10,
        numResources: 2,
        devRequired: "Backend Developer, Mobile App Developer",
        recommendedStack: ["Python Django", "React native"],
      },
    ],
  },
];